apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/app/helloworld
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}