apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    targetRevision: master
    chart: charats/ingress-nginx
    repoURL: https://github.com/kubernetes/ingress-nginx.git
  syncPolicy:
    automated: {}