apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: wireguard
spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/app/wireguard
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true