apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - public.yaml
  - github.com/kryptn/infra/cluster?ref=HEAD
  - private.yaml
  - github.com/kryptn/infra-private/applications?ref=HEAD
  - github.com/kryptn/infra/projects?ref=HEAD
