apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- infrastructure.yaml
- github.com/kryptn/infra/applications/infrastructure?ref=HEAD
- public.yaml
- github.com/kryptn/infra/applications/public?ref=HEAD
- private.yaml
- github.com/kryptn/infra-private/projects?ref=HEAD
- projects.yaml

