apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrapper
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: projects
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}