
step1:
    kustomize build ../apps/sealed-secrets | kubectl apply -f -
    kustomize build ../apps/ingress-nginx | kubectl apply -f -

step2:
    just ../ seal-all-secrets

step3:
    kustomize build ../apps/cert-manager/ | kubectl apply -f -
    kustomize build ../apps/external-dns/ | kubectl apply -f -

step4:
    kustomize build ../apps/argo-cd/ | kubectl apply -f -
