
update version:
    kustomize edit set image ghcr.io/kryptn/newreleases-dispatch-action:latest=ghcr.io/kryptn/newreleases-dispatch-action:{{version}}

seal-secret:
    kubectl -n newreleases-dispatch-action create secret generic newreleases-dispatch-action-secret --dry-run=client --from-env-file=newreleases-dispatch-action.env -o json > newreleases-dispatch-action.env.json
    cat newreleases-dispatch-action.env.json | kubeseal --controller-namespace sealed-secrets > newreleases-dispatch-action-secret.json
