apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- svc.yaml
- newreleases-dispatch-action-secret.json
namespace: newreleases-dispatch-action
commonLabels:
  app: newreleases-dispatch-action
images:
- name: ghcr.io/kryptn/newreleases-dispatch-action:latest
  newName: ghcr.io/kryptn/newreleases-dispatch-action
  newTag: v0.2.0
