apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
- ns.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- configmap.yaml
- sealed-vaultwarden-secret.json