apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: kryptn@gmail.com
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: cert-manager-digitalocean-token
            key: do_token
        ingress:
          class: nginx