apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# https://cert-manager.io/docs/installation/kubernetes/
# wget https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml -O cert-manager.yaml
- cert-manager.yaml
- issuer.yaml
- sealed-do-token.json