apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: cert-manager

resources:
# https://cert-manager.io/docs/installation/kubernetes/
- cert-manager.yaml
- issuer.yaml
- sealed-cert-manager-digitalocean-token.json
