name: "update kustomize image tag"
description: "updates a kustomization file with a new image tag"
inputs:
  app-dir:
    required: true
    type: string
  branch:
    required: true
    type: string
  version:
    required: true
    type: string
  project:
    required: true
    type: string
  github-token:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Prepare Git
      shell: bash
      env:
        BRANCH: "auto/${{ inputs.branch }}"
      run: |
        git config --global user.name "kbot"
        git config --global user.email "kryptn@users.noreply.github.com"
        git fetch origin

        # switch if exists, else create new from main
        git switch $BRANCH || git switch -c $BRANCH
        git --no-pager log  --oneline -n 5

    - name: Update image tag
      uses: mikefarah/yq@master
      env:
        VERSION: ${{inputs.version}}
        APP_DIR: ${{inputs.app-dir}}
      with:
        cmd: yq -i '.images[].newTag = "$VERSION"' "$APP_DIR/kustomization.yaml"

    - name: Commit and Push Update
      shell: bash
      env:
        BRANCH: "auto/${{ inputs.branch }}"
        VERSION: ${{inputs.version}}
      run: |
        git rev-parse --abbrev-ref HEAD
        git --no-pager log  --oneline -n 5

        git add .
        git status
        git commit -m "automated bump to version $VERSION"
        git push origin auto/$BRANCH

    - name: pull-request
      uses: repo-sync/pull-request@v2
      env:
        PROJECT: ${{inputs.project}}
        BRANCH: "auto/${{ inputs.branch }}"
        TOKEN: ${{inputs.github-token}}
      with:
        pr_title: "Updating $PROJECT"
        source_branch: "$BRANCH"
        destination_branch: main
        github_token: "$TOKEN"
