version: "3"


tasks:
  bootstrap:
    cmds:
      - kustomize build argocd-bootstrap | kubectl apply -f -

  admin-pw:
    cmds:
      - kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2

  deploy-core:
    cmds:
      - kubectl apply -f resources/bootstrap.yaml

  port-forward:
    cmds:
      - task: admin-pw
      - kubectl port-forward svc/argocd-server -n argocd 8080:443

  deploy:
    cmds:
      - task: bootstrap
      - task: deploy-core
      - task: admin-pw