version: "3"


tasks:
  pull-master-key:
    cmds:
      - kubectl get secret -n sealed-secrets -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > secrets/master.yaml

  replace-master-key:
    cmds:
      - kubectl apply -f secrets/master.yaml

 generate-secrets:
    cmds:
      - ./seal_secrets.sh

