apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: public
  source:
    path: apps/vaultwarden
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}