apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- controller-v0.14.1.yaml
# - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.14.1/controller.yaml

namespace: sealed-secrets

commonLabels:
  app: sealed-secrets

# patchesJson6902:
# - target:
#     version: apiextensions.k8s.io/v1
#     kind: CustomResourceDefinition
#     name: sealedsecrets.bitnami.com
#   path: delete-properties.yaml