apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami-labs/sealed-secrets/releases/latest
resources:
- namespace.yaml
- controller.yaml
# wget https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml -O cert-manager.yaml



namespace: sealed-secrets

commonLabels:
  app: sealed-secrets

