apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami-labs/sealed-secrets/releases/latest
resources:
- namespace.yaml
- controller.yaml
# wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml -O controller.yaml



namespace: sealed-secrets

commonLabels:
  app: sealed-secrets

