apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.14.1/controller.yaml

namespace: sealed-secrets

commonLabels:
  app: sealed-secrets