apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- controller.yaml
#- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.15.0/controller.yaml

namespace: sealed-secrets

commonLabels:
  app: sealed-secrets

# patchesJson6902:
# - path: delete-properties.yaml
#   target:
#     group: apiextensions.k8s.io
#     version: apiextensions.k8s.io/v1
#     kind: CustomResourceDefinition
#     name: sealedsecrets.bitnami.com
