---
# Source: tailscale-relay/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-relay
  annotations:    
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
---
# Source: tailscale-relay/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-subnet-router-tailscale-relay-config
  annotations:    
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
type: Opaque
stringData:
  TAILSCALE_AUTH_KEY: foo
---
# Source: tailscale-relay/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-subnet-router-tailscale-relay-config
  annotations:    
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
data: 
  {}
---
# Source: tailscale-relay/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-subnet-router-tailscale-relay
  annotations:    
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
rules:
  - apiGroups: [""]
    # TODO: Troubleshoot as for some obscure reason it doesn't seem to work
    # when being scoped down to a single resource
    # resourceNames: [ tailscale-relay-state ]
    resources: ["secrets"]
    verbs: ["create", "get", "update"]
---
# Source: tailscale-relay/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-subnet-router-tailscale-relay-tailscale-relay
  annotations:    
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
subjects:
  - kind: ServiceAccount
    name: tailscale-relay
roleRef:
  kind: Role
  name: tailscale-subnet-router-tailscale-relay
  apiGroup: rbac.authorization.k8s.io
---
# Source: tailscale-relay/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale-subnet-router-tailscale-relay
  labels:    
    helm.sh/chart: tailscale-relay-0.1.1
    app.kubernetes.io/name: tailscale-relay-0.1.1
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: tailscale-relay
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: tailscale-subnet-router
    app.kubernetes.io/version: v1.18.2
  annotations:    
spec:
  replicas: 1
  selector:
    matchLabels:      
      app.kubernetes.io/name: tailscale-relay-0.1.1
      app.kubernetes.io/instance: tailscale-subnet-router
  serviceName: tailscale-relay
  template:
    metadata:
      labels:        
        helm.sh/chart: tailscale-relay-0.1.1
        app.kubernetes.io/name: tailscale-relay-0.1.1
        app.kubernetes.io/component: tailscale
        app.kubernetes.io/part-of: tailscale-relay
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: tailscale-subnet-router
        app.kubernetes.io/version: v1.18.2

      annotations:
        checksum/configMap: 9523f23be8ba49c095f969a7971081c47dad825e5adcb4457174177727b444c3
        checksum/secret: ab37636559fb1abdd4963cc1e8b96f979be9467b3a04e5ae71d3a66dacdc5d2b        

    spec:
      hostNetwork: false
      serviceAccountName: tailscale-relay
      containers:
        - name: tailscale-relay
          image: docker.io/mvisonneau/tailscale:v1.18.2
          imagePullPolicy: IfNotPresent
          env:
            - name: TAILSCALED_STATE
              value: kube:tailscale-relay-state
          envFrom:
            - configMapRef:
                name: tailscale-subnet-router-tailscale-relay-config
            - secretRef:
                name: tailscale-subnet-router-tailscale-relay-config
          ports:
            - name: exporter
              containerPort: 8080
              protocol: TCP
          securityContext: 
                capabilities:
                  add:
                  - NET_ADMIN
