apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - namespace.yaml
  - generated-helm-tailscale.yaml
  - sealed-tailscale-relay-config.json

patches:
  - path: env-patch.yaml
    target:
      kind: StatefulSet