apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newreleases-dispatch-action
  namespace: argocd
spec:
  destination:
    namespace: newreleases-dispatch-action
    server: https://kubernetes.default.svc
  project: public
  source:
    path: apps/newreleases-dispatch-action
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true