apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress
bases:
  - github.com/kubernetes/ingress-nginx/deploy/static/provider/do?ref=master
resources:
  - namespace.yaml