apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd

spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    path: apps/external-dns
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true