apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/external-dns
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}