apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd

spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v3.21.0
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: arq.dev,*.arq.dev,kryptn.com,*.kryptn.com
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true