apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v3.21.0
    chart: ingress-nginx
    helm:
      parameters:
      - name: service.annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: "*.arq.dev,arq.dev"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true