apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster.yaml
- argo-cd.yaml
- argo-workflows.yaml
- ingress-nginx.yaml
- cert-manager.yaml
- external-dns.yaml
# - helloworld.yaml
- kryptn-com.yaml
- httpbin.yaml
- sealed-secrets.yaml
# - thelounge.yaml
- websub-listener.yaml
# - wireguard.yaml
- nats-operator.yaml
