apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-operator
  namespace: argocd

spec:
  destination:
    namespace: nats-io
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 0.7.4
    chart: nats/nats-operator
    helm:
      values: |
        clusterScoped: true
        replicaCount: 3
        auth:
          enabled: false
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true