apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thelounge
  namespace: argocd

spec:
  destination:
    namespace: thelounge
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/thelounge
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true