apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: websub-listener
  namespace: argocd

spec:
  destination:
    namespace: websub-listener
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/websub-listener
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true