apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

# https://github.com/kubernetes-sigs/external-dns/releases/latest
resources:
- namespace.yaml
- github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.10.0
- sealed-do-token.json

patches:
- path: digitalocean.yaml
  target:
    kind: Deployment