apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

# https://github.com/kubernetes-sigs/external-dns/releases/latest
resources:
- namespace.yaml
- generated-external-dns.yaml
- sealed-do-token.json
- ../podlogs

patches:
- path: digitalocean.yaml
  target:
    kind: Deployment