apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

secretGenerator:
- name: digitalocean-token
  envs:
  - ../../secrets/do_token.env

bases:
- https://github.com/kubernetes-sigs/external-dns/kustomize@master