apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://raw.githubusercontent.com/grafana/agent/main/production/kubernetes/agent-bare.yaml
# NAMESPACE=grafana-agent /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/kubernetes/install-bare.sh)" > agent-bare.yaml
resources:
- agent-bare.yaml

namespace: grafana-agent

commonLabels:
  app: grafana-agent