apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - install.yaml
  - argo-cd-ingress.yaml
  - sealed-gh-token.json

# changes to config maps
patches:
- path: overlays/argo-cd-cm.yaml
  target:
    kind: ConfigMap

# patchesStrategicMerge:
# - overlays/kustomize-custom-tool.yaml
