apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:

  - namespace.yaml
  - install.yaml
  - argo-cd-ingress.yaml

# changes to config maps
patches:
- path: overlays/argo-cd-cm.yaml
  target:
    kind: ConfigMap

