apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:

  - namespace.yaml
  - install.yaml


# changes to config maps
patchesStrategicMerge:
  - overlays/argo-cd-cm.yaml