apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - secret

resources:

  - namespace.yaml
  - install.yaml

# secretGenerator:
#   - name: argo-cd-github-token
#     env: github_token.env


# changes to config maps
patchesStrategicMerge:
  - overlays/argo-cd-cm.yaml