apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # https://github.com/argoproj/argo-cd/releases/latest
  - generated-argo-cd.yaml
  - namespace.yaml
  - argo-cd-ingress.yaml
  - sealed-argocd-github-token.json
  - sealed-argocd-github-oidc-token.json

# changes to config maps
patches:
  - path: overlays/argo-cd-cm.yaml
    target:
      kind: ConfigMap
  - path: overlays/argocd-rbac.yaml
    target:
      kind: ConfigMap
  - path: add-managed-label.yaml
    target:
      kind: SealedSecret
      name: argocd-github-oidc-token

