apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # https://github.com/argoproj/argo-cd/releases/latest
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.1.1
  - namespace.yaml
  - argo-cd-ingress.yaml
  - sealed-gh-token.json
  - sealed-gh-odic-secret.json

# changes to config maps
patches:
  - path: overlays/argo-cd-cm.yaml
    target:
      kind: ConfigMap
  - path: overlays/argocd-rbac.yaml
    target:
      kind: ConfigMap
  - path: patch-remove-argocd-secret.yaml
    target:
      kind: Secret
      name: argocd-secret
# patchesStrategicMerge:
# - overlays/kustomize-custom-tool.yaml
