apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
  - name: external-dns-digitalocean-token
    envs: do_token.env