apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-cd.yaml
  # - argo-workflows.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - grafana-stack.yaml
  - ingress-nginx.yaml
  - nats-operator.yaml
  - opentelemetry-operator.yaml
  - sealed-secrets.yaml
  # - honeycomb.yaml
  - tailscale.yaml
