
update version:
    helm template kube-prometheus-stack --repo="https://prometheus-community.github.io/helm-charts" --version={{version}} --include-crds --values=values.yaml kube-prometheus-stack > kube-prometheus-stack.yaml