apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-stack

resources:
- kube-prometheus-stack.yaml
- namespace.yaml

patches:
- path: replace-annotation-crd-patch.yaml
  target:
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com