apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-wireguard
  namespace: wireguard
spec:
  storageClassName: "do-block-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
