---
# Source: honeycomb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: honeycomb
  labels:
    helm.sh/chart: honeycomb-1.0.4
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: honeycomb/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: honeycomb-agent
  labels:
    helm.sh/chart: honeycomb-1.0.4
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: agent
data:
  config.yaml: |
    apiHost: https://api.honeycomb.io/
    watchers:
      - dataset: kubernetes-logs
        labelSelector: component=kube-controller-manager
        namespace: kube-system
        parser: glog
      - dataset: kubernetes-logs
        labelSelector: component=kube-scheduler
        namespace: kube-system
        parser: glog
    verbosity: info
    splitLogging: false

    metrics:
      clusterName: k8s-cluster
      dataset: kubernetes-metrics
      enabled: true
      metricGroups:
      - node
      - pod
---
# Source: honeycomb/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honeycomb-agent
  labels:
    helm.sh/chart: honeycomb-1.0.4
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: agent
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes/stats
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
---
# Source: honeycomb/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: honeycomb-agent
  labels:
    helm.sh/chart: honeycomb-1.0.4
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: honeycomb-agent
subjects:
  - kind: ServiceAccount
    name: honeycomb
    namespace: default
---
# Source: honeycomb/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: honeycomb-agent
  labels:
    helm.sh/chart: honeycomb-1.0.4
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: agent
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: honeycomb
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: agent
  template:
    metadata:
      annotations:
        checksum/config: 63345923777ce5323dcd3ead783451918244db541c50e731c1b7069852a6bcaf
      labels:
        app.kubernetes.io/name: honeycomb
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: honeycomb
      securityContext:
        {}
      containers:
        - name: honeycomb-agent
          securityContext:
            {}
          image: "honeycombio/honeycomb-kubernetes-agent:2.1.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: HONEYCOMB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: api-key
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: "/etc/honeycomb"
              readOnly: false
            - name: varlog
              mountPath: "/var/log"
              readOnly: false
            - name: varlibdockercontainers
              mountPath: "/var/lib/docker/containers"
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: honeycomb-agent
        - name: varlog
          hostPath:
            path: "/var/log"
        - name: varlibdockercontainers
          hostPath:
            path: "/var/lib/docker/containers"
      tolerations:
        - effect: NoSchedule
          key: node.alpha.kubernetes.io/role
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
