
update version:
    helm template grafana-agent-operator --repo https://grafana.github.io/helm-charts --include-crds --version {{version}} --values values.yaml grafana-agent-operator > grafana-agent.yaml