apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: honeycomb
  namespace: argocd
spec:
  destination:
    namespace: honeycomb
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: apps/honeycomb
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
