apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: apps/opentelemetry-operator
    repoURL: https://github.com/kryptn/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true