apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websub-listener-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: websub.arq.dev
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: websub-listener-service
            port:
              number: 80
  tls:
  - hosts:
    - websub.arq.dev
    secretName: websub-listener-cert
