apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websub-listener

resources:
- namespace.yaml
- ingress.yaml
- sealed-websub-config.json
- github.com/kryptn/websub-listener/deploy/kustomize?ref=v0.1.2
- ../podlogs


commonLabels:
  app: websub-listener

images:
- name: kryptn/websub-listener
  newTag: v0.1.3