apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- ./namespace.yaml
- ../base/
- ./sealed-vault-storage.json

patches:
  - path: vault-config.yaml
  - path: env-from.yaml
    target:
      kind: StatefulSet
      name: vault