on:
  repository_dispatch:
    types: [newreleases]

jobs:
  poc:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'kryptn/something-else'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "dispatched"

  update-app-poc:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'kryptn/newreleases-dispatch-action'}}
    runs-on: ubuntu-latest
    steps:

      - name: Show Info
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: echo "updating app to $VERSION"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "main"

      - name: Prepare Git
        run: |
          git config --global user.name "kryptn"
          git config --global user.email "kryptn@users.noreply.github.com"
          git remote -v
          git branch -v -a

          git fetch origin
          # git fetch origin auto/update-newreleases-new || echo "no remote branch auto/update-newreleases-new"
          git switch -c auto/update-newreleases-new && echo "created new" || git switch auto/update-newreleases-new && echo "using existing"
          # git pull origin auto/update-newreleases-new
          # git pull origin main --ff-only
          git pull origin auto/update-newreleases-new || echo "no remote branch auto/update-newreleases-new"
          git rev-parse --abbrev-ref HEAD
          git --no-pager log  --oneline -n 5

      - name: Update image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.images[].newTag = "${{ github.event.client_payload.version }}"' "./apps/newreleases-dispatch-action/kustomization.yaml"

      - name: Commit and Push Update
        working-directory: ./apps/newreleases-dispatch-action
        run: |
          git rev-parse --abbrev-ref HEAD
          git --no-pager log  --oneline -n 5

          git add .
          git status
          git commit -m "automated bump to version ${{ github.event.client_payload.version }}"
          git rev-parse --abbrev-ref HEAD

          git push origin auto/update-newreleases-new
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Updating ${{ github.event.client_payload.project }}"
          source_branch: "auto/update-newreleases-new"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
