on:
  repository_dispatch:
    types: [newreleases]

jobs:

  update-app:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'kryptn/newreleases-dispatch-action'}}
    # if: ${{ contains(['kryptn/newreleases-dispatch-action', ], github.event.client_payload.project) }}
    uses: kryptn/infra/.github/workflows/update-image.yaml@main
    with:
      app-dir: ./apps/newreleases-dispatch-action
      branch: update-newreleases
      version: ${{github.event.client_payload.version}}
      project: ${{github.event.client_payload.project}}

