on:
  repository_dispatch:
    types: [newreleases]

jobs:

  update-newreleases:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'kryptn/newreleases-dispatch-action'}}
    # if: ${{ contains(['kryptn/newreleases-dispatch-action', ], github.event.client_payload.project) }}
    uses: kryptn/infra/.github/workflows/update-image.yaml@main
    with:
      app-dir: ./apps/newreleases-dispatch-action
      branch: update-newreleases
      version: ${{github.event.client_payload.version}}
      project: ${{github.event.client_payload.project}}

  update-argocd:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'argoproj/argo-cd'}}
    # if: ${{ contains(['kryptn/newreleases-dispatch-action', ], github.event.client_payload.project) }}
    uses: kryptn/infra/.github/workflows/kustomize-build.yaml@main
    with:
      app-dir: ./apps/argo-cd
      branch: update-argocd
      version: ${{github.event.client_payload.version}}
      project: ${{github.event.client_payload.project}}
      title: ${{github.event.client_payload.note.title}}
      message: ${{github.event.client_payload.note.message}}

  update-vaultwarden:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'dani-garcia/vaultwarden'}}

    uses: kryptn/infra/.github/workflows/update-image.yaml@main
    with:
      app-dir: ./apps/vaultwarden
      branch: update-vaultwarden
      version: ${{github.event.client_payload.version}}
      project: ${{github.event.client_payload.project}}

  update-external-dns:
    if: ${{ github.event.client_payload.provider == 'github' && github.event.client_payload.project == 'kubernetes-sigs/external-dns'}}
    uses: kryptn/infra/.github/workflows/kustomize-build.yaml@main
    with:
      app-dir: ./apps/external-dns
      branch: update-external-dns
      version: ${{github.event.client_payload.version}}
      project: ${{github.event.client_payload.project}}
      title: ${{github.event.client_payload.note.title}}
      message: ${{github.event.client_payload.note.message}}