on:
  repository_dispatch:
    types: [newreleases-test]

jobs:

  do-update:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context)
            const projects = require("./.github/workflows/newreleases.json")
            console.log(projects)

            const valid = projects[context.client_payload.project] != undefined
            core.setOutput('valid', valid)

            if (valid) {
              core.setOutput('app_dir', projects[context.client_payload.project].app_dir)
              core.setOutput('branch_name', projects[context.client_payload.project].branch_name)
              core.setOutput('version', context.client_payload.version)
            }

      - name: setup-kustomize
        uses: imranismail/setup-kustomize@v1

      - name: setup-helm
        uses: azure/setup-helm@v1

      - name: setup-just
        uses: extractions/setup-just@v1