on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
      branch:
        required: true
        type: string
      version:
        required: true
        type: string
      project:
        required: true
        type: string
      base:
        required: false
        type: string
        default: 'main'
    secrets:
      token:
        required: true

jobs:

  update-image-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "main"

      - name: Prepare Git
        run: |
          git config --global user.name "kbot"
          git config --global user.email "kryptn@users.noreply.github.com"
          git fetch origin

          # switch if exists, else create new from main
          git switch auto/${{ inputs.branch }} || git switch -c auto/${{ inputs.branch }}
          git --no-pager log  --oneline -n 5

      - name: Update image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.images[].newTag = "${{ inputs.version }}"' "${{ inputs.app-dir }}/kustomization.yaml"

      - name: Commit and Push Update
        # working-directory: ${{ inputs.app-dir }}
        run: |
          git rev-parse --abbrev-ref HEAD
          git --no-pager log  --oneline -n 5

          git add .
          git status
          git commit -m "automated bump to version ${{ inputs.version }}"
          git push origin auto/${{ inputs.branch }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Updating ${{ inputs.project }}"
          source_branch: "auto/${{ inputs.branch }}"
          destination_branch: ${{ inputs.base }}
          github_token: ${{ secrets.token }}
